Part provider rewrite
FaeCraft/Heart-Shaped-Box pull request #1
Opened 2021-01-09 03:54 UTC by P03W

Rewrites parts to be identifier based
- All parts are stored in a single ArrayList
- Limbs and providers can be (fairly) easily serialized to and from tags
- There is a class with lenses/getters for the default limbs
- FlexBox updating still needs to be rewritten to better support dynamic parts, but works in its current state

2021-01-09 12:43 UTC, gdude2002 requested changes
Overall not bad, but I have a few design-related concerns that I've created comments for.

2021-01-09 12:43 UTC, gdude2002 commented on src/main/java/io/github/faecraft/heartshapedbox/body/BuiltInParts.java
> +    public static final Identifier HEAD = new Identifier("hsb:head");
`hsb` does not match the mod ID — stick a constant in a common class and refer to that in the first param instead of trying to copy-paste it with a colon everywhere

2021-01-09 12:43 UTC, gdude2002 commented on src/main/java/io/github/faecraft/heartshapedbox/body/impl/ArmBodyPart.java
> +        this.identifier = new Identifier("hsb:arm/" + side.lowerName());
It doesn't make much sense to create an identifier here when we already have a constant stored for it. Actually, aside from the max health, it doesn't seem like we even need an abstract class any more — can we have a generic body part type that you just instantiate to create a body part, for when you don't really need a subclass?

2021-01-09 12:43 UTC, gdude2002 commented on src/main/java/io/github/faecraft/heartshapedbox/body/impl/FootBodyPart.java
> +        this.identifier = new Identifier("hsb:foot/" + side.lowerName());
See comment on `ArmBodyPart`.

2021-01-09 12:43 UTC, gdude2002 commented on src/main/java/io/github/faecraft/heartshapedbox/body/impl/HeadBodyPart.java
> +    private final Identifier identifier = new Identifier("hsb:head");
See comment on `ArmBodyPart`.

2021-01-09 12:43 UTC, gdude2002 commented on src/main/java/io/github/faecraft/heartshapedbox/body/impl/LegBodyPart.java
> +    private final Identifier identifier;
See comment on `ArmBodyPart`.

2021-01-09 12:43 UTC, gdude2002 commented on src/main/java/io/github/faecraft/heartshapedbox/mixin/BodyPartDuck.java
> +    private final ArrayList<AbstractBodyPart> parts = new ArrayList<>();
Is a list the most efficient way to do this, or would a map of `Identifier` to `BodyPart` make more sense?

2021-01-09 12:43 UTC, gdude2002 commented on src/main/java/io/github/faecraft/heartshapedbox/mixin/BodyPartDuck.java
> +        return maybeGet(identifier).get();
Perhaps a `getOrNull` may be useful as well

2021-01-09 16:30 UTC, P03W commented on src/main/java/io/github/faecraft/heartshapedbox/body/impl/ArmBodyPart.java
> +        this.identifier = new Identifier("hsb:arm/" + side.lowerName());
Yeah I'll definitely fix the identifier duplication, but I'm against making a single BodyPart class because it would make updating flex boxes for arbitrary parts harder

Something I'd like to eventually be possible is for mods to add or replace body parts (i.e for some sort of morph mod) and making a *BodyPart update its own flex boxes seems the easiest way to do that, which isn't as easy if there's only a single BodyPart class

2021-01-09 19:56 UTC, P03W commented
Oops, thought that was a refresh button instead, apologies

2021-01-12 11:23 UTC, gdude2002 commented
I'm fairly happy with this, I think we can certainly work with it. I'll merge it now — I think there are still improvements we can make, but I don't think they're necessary for us to be able to continue our work here.

2021-01-12 11:23 UTC, merged